require('globals')
require('ui')
require('options')
require('keymaps')
require('autocmd')
require('commands')
require('statusline')
require('lsp')
require('formatter')
require('dap-config')
require('plugins')

