require('globals')
require('options')
require('keymaps')
require('autocmd')
require('commands')
require('lsp')
require('completion')
require('treesitter')
require('dap-config')
require('statusline')
require('plugins')
require('telescope-config')
require('notes')
require('themes')

